---
repos:
  - repo: local
    hooks:
      - id: check
        name: check
        entry: make check
        language: system
        pass_filenames: false
        files: ^(README\.md|.*\.py)$
      - id: lint-md
        name: lint markdown
        entry: make lint-md
        language: system
        pass_filenames: false
        types: [markdown]
