services:
  sd-creation-wizard-api:
    build:
      context: submodules/sd-creation-wizard-api
      dockerfile: deployment/docker/Dockerfile
    image: sd-creation-wizard-api:local
    container_name: sd-creation-wizard-api
    ports:
      - "8080:8080"

  sd-creation-wizard:
    build:
      context: submodules/sd-creation-wizard-frontend
      dockerfile: deployment/docker/Dockerfile
    image: sd-creation-wizard:local
    container_name: sd-creation-wizard
    ports:
      - "4200:80"
    depends_on:
      - sd-creation-wizard-api
    environment:
      - API_URL=http://localhost:8080
